### PR TITLE
Fixing some errors in the release workflow

### PR DESCRIPTION
**Pull request by MohamedNasser8**

### CODE REVIEW

**Comment by MohamedNasser8** [comment]
I think it should work now without errors @ltorres6

**Comment by ltorres6** [comment]
Thanks Mohamed. Can you add a configuration option to select which repository we want to publish to? I'd like to be able to test by publishing to https://test.pypi.org/. This should be a similar configuration setup as you have for the "major/minor/patch" config.

Additionally, please set up the workflow to automatically use the user's information (who is running the workflow) for the git commands.

**Comment by MohamedNasser8** [comment]
I think it should work now, the error I get is related to trusted publisher configuration @ltorres6

**Review by ltorres6 — APPROVED** [review]
LGTM. I fixed the error you were having on testpypi. https://test.pypi.org/project/osipi/4.0.0/

**Comment by ltorres6** [comment]
Sorry, I noticed we aren't actually creating releases on github, which we should do in the pipeline. Please add this. Additionally, we should include all notes from PR merges in the release notes. This will involve looking up the notes between the previous release and the current one and including it in the release notes body.

**Pull request merged**
